### ISSUE TITLE
Buff Notification Bug

### ISSUE THREAD

**Issue by Xaikii** [GenDeathrow/PlayerRaiders#10]
I am having a wierd issue rn.
The Notification that Raiders got buffed is basically not appearing.

**Recreation**:

1.Open Chat
2.Wait until the Day Raiders should get buffed
3.Run Command /gamestage add VAR_NAME VAR_STAGE (at least in my case was it that command) [VAR_NAME stand for Player's Name and VAR_STAGE for any Stage]

**What I expect to happen**:

Normal Behaviour / Buff Notification appearing and disappearing.

**What happens**:

The Notification trying to appear but unable to. + Sound Spam since it tries it permanently.

**Possible Cause**:

Since I have the full GameStages set, and I think it is OreStages it is reloading the world and/or resources after running the command.

I do want to note that this may **not** be the cause, but since it happens in combination with it and never before I can only assume this.

**Comment by GenDeathrow** [comment]
That's interesting. I will look into it. but my guess is a world re-log fixes it for now? Sounds like it gets into a loop somehow. I will have to see what gamestages/orestages is doing. 

Also make sure to include mc and mod version. I figured it out on the mc version cause of game stages mod.

**Comment by Xaikii** [comment]
Yep rejoining any World fix that, still it will show every Notification again

Yes sry ^^ ' 
I thought it was obvious because of GameStages

**Comment by GenDeathrow** [comment]
Its all cool, you wrote a good issue. I just cant be sure if your what version of the mod/mc your using. Im going to guess its is the latest 3.0.1 version.

**Comment by TylerCrazyWolf** [comment]
I'm using the latest version of Minecraft and the mod and I have the same issue every single time... it's quite annoying. It happens no matter what.

can't use commands to fix it since my world is hardcore, reloading the world and/or Minecraft doesn't fix the issue either. The notification will spam me unless I remove the mod so basically the mod is unplayable at the moment for me...

**Comment by GenDeathrow** [comment]
Are you using Gamestages as well @TylerCrazyWolf? And you can stop the notifications by disabling raid difficulty, but that removes the raiders from getting harder over time. .

**Comment by Xaikii** [comment]
At this point I do have to add that today it happened to me without Gamestages. 
I died, respawned, at the same time Mobs got buffed, GUI Notificatiom got stuck in a loop.

**Comment by GenDeathrow** [comment]
Its strange its happening because it was featured in Invasion modpack in 1.10, and never did this(or never reported).. So this is either a 1.11+ / 1.12 issue. I may have to rewrite the way its triggered. I appreciate the input. Hopefully I can get this fixed fast. But I may be flying blind cause I cant seem to recreate it. But I will try the last suggestion.

**Comment by GenDeathrow** [comment]
Is this a particular modpack? or just something you have put together? I only ask because I cant recreate whats happening here.  

Can you recreate it with just Raiders installed?

**Comment by GenDeathrow** [comment]
What I will do for now is add a settings to turn off the gui for the time being. Although any information still is going to help fix this.

**Comment by Xaikii** [comment]
I am using this in my modpack, it is still in Alpha because of still existing bugs etc. ^^'

Anyways the recreation could be a hard thing since I can't really force it, it basically happens randomly.
If somehow possible I'd like to still help probably with a debug command? so that when it happens I could run the command and that may help with the problem ^^

**Comment by GenDeathrow** [comment]
Well while making the debug command.. I now think I see whats happening. I think it is happening because of FPS rendering speed and just strange interaction with it.. I do some more testing.

**Comment by GenDeathrow** [comment]
Ok I think I got this fixed up.. I did add a debug command. But I hope I have actually fixed the issue. 

/raiders debugmode <true/false>

it will print in the log file

**Comment by GenDeathrow** [comment]
Pushing an update out.. test see if this fixes your issue at all.. if it doesn't use the debug command and it should show when it sends a receives the updates in the logs

**Comment by GenDeathrow** [comment]
@Xaikii any idea if this fixed that issue?

**Comment by Xaikii** [comment]
Didn't get the issue yet again, I am going report directly if it happens again, I guess if it doesnt happen in the next 3 days again, we could consider it as fixed

**Comment by GenDeathrow** [comment]
Well I hope so.. thanks for the quick response. I will leave this open for 3 days.. than close.

**Comment by Xaikii** [comment]
Did not occur again, so I am going to close this ^^
