### ISSUE TITLE
\config\raiders\raider_classes.json seems to reset to default values on each launch.

### ISSUE THREAD

**Issue by TeetoKaziim** [GenDeathrow/PlayerRaiders#14]
Trying to set different raiders to not show up until later raid, difficulties, and/or adjust their relative weights, but the .json is reverted to defaults every time the game loads.

**Comment by GenDeathrow** [comment]
I'll look into that soon

**Comment by GenDeathrow** [comment]
Sorry was taking a break on modding, getting a fix on this tonight now. Sorry for the inconvenience.

**Comment by GenDeathrow** [comment]
should be fixed 3.0.5

**Comment by TeetoKaziim** [comment]
Nono, this is cool. We're all doing this minecraft stuff for fun, even those of us coding. Thanks a bunch!
