### ISSUE TITLE
Static Mobs

### ISSUE THREAD

**Issue by ghost** [GenDeathrow/PlayerRaiders#17]
so when the raiders spawn we got a lot on the server that just stand still. You can attack them once then they take no damage

this happens quite a lot.  Ive had to disable the Witchs too because they just sit there and you cant attack them (dont know if this is intentional) (you also cant /Kill them)

Forge 2707
Raiders 3.0.5 (1.12)

**Comment by GenDeathrow** [comment]
I'm not really sure on that, I haven't ever heard this or seen it before.  I would prolly need some type of video to understand it better. It would be hard to recreate that because I have no way of know how to recreate it. Do you happen to have friendly raiders on? Even if you do you should be able to damage them. 

As far as witches they sit, and you cant kill them when they are sitting. although killing commands should work, but it may not (i'll test that later). If your in creative Witches don't activate and wont attack ya., and cant be killed on purpose. Its meant so players cant just kill them from a distance.

**Comment by ghost** [comment]
https://youtu.be/AAwTvbh8Tyg?t=56m19s (watch up to 57:40, and at 58:40)  3 mobs wont take damage)  is one that i can find.  

i had it for a bit on my singleplayer, i changed to the ExtraUtils Kikoku sword from a stone sword and the mob took damage. weird. https://youtu.be/LABH26aYQ2Q

**Comment by GenDeathrow** [comment]
So if you run raiders only, does this happen? I only ask cause I am not seeing this issue happen in my testing. To me it seems like another mod is possibly modifying raiders. Also seeing some graphic glitches from those videos.

**Comment by ghost** [comment]
So I need to do more testing for the static mobs part, but there is still gfx glitching with only the Raiders mod loaded, with and without Optifine

maybe its a forge thing? Using Forge 2707  Minecraft 1.12.2

**Comment by GenDeathrow** [comment]
It shouldn't be, I haven't seen the glitch ever before.  Did you say you had more bends? I wouldn't think that would do it, but it does mess with rendering of entitites. Something is changing rendering.

**Comment by ghost** [comment]
As to the texture glitching, I had the same problem today using CustomNPC mod. Seemed to be when using 4 pixel wide skins, could that be the issue?

**Comment by GenDeathrow** [comment]
4 pixel wide skins?

**Comment by ghost** [comment]
you know Minecraft has classic and slim skins? on the Mojang website when you sign in and upload a skin it asks you which size it is

its mainly the arm width I believe, 3 or 4 pixels,  but I had rendering issues with CustomNPCs and its the only thing i could think off

**Comment by GenDeathrow** [comment]
Well I personally use the Steve style skin for all my mods. but it technically supports both Steve and Alex style skins. I don't think that would cause it.. cause all it depends on is the size of the image. But couldn'
t tell ya for sure atm.

**Comment by ghost** [comment]
So it seems that player skins and mob skins are rendered different (or even saved differently?)
So I used MCreator (minecraft mod maker) to create a simple mob. I had the model set to Biped and used a 'drowned' skin that i donwloaded from somewhere. It came out all topsy turvy.

After setting the Model type to Zombie the skin generated fine on the mob

So it was probably my fault for downloading mob skins instead of player skins? or something?

**Comment by GenDeathrow** [comment]
I'll see about maybe handling the issue a bit better like maybe telling the player when there is an incompatible skin size. But they do have to basically be player skins layouts with certain image size or it will not render properly. Model skins can be very particular to the mob.  I mean I cant be perfect on that ,cause all I can really tell is if the img is the correct size.
