### ISSUE TITLE
world load crash

### ISSUE THREAD

**Issue by ghost** [GenDeathrow/PlayerRaiders#18]
i believe i have 3 skins that cause Raiders to fail loading the world
they were downloaded from http://minecraft.tools/en/skin.php

I changed the entries in the raiders_skins file to enabled=false and the game crashed
I removed the entries from the raiders_skins file and the game crashed
I had to remove the skins from the assets/skins folder and the game loaded

crash report  https://pastebin.com/5PR1u55d

Forge 2707
Raiders 3.0.5 (1.12)

**Comment by GenDeathrow** [comment]
... ahh I think you may have helped me narrow down a crash I was trying to figure out. Any chance you can pastebin your config file for your raiders?

**Comment by ghost** [comment]
so this is the settings config file https://pastebin.com/yD1uAYaq
this is the skins config file https://pastebin.com/Mq0juFNE
i thought thecheesemo, pfunk_me and revlis_lost skins were causing the crash, if removed from skins folder and deleted from config it wouldnt crash, at the time of writing this it still crashes with said skins removed    https://www.dropbox.com/s/1ypjl324g3kozbq/Everyone%20in%20Skins.rar?dl=0

ive never used dropbox if the link fails let me know

With optifine and foamfix removed it crashes if they would make any difference?

**Comment by ghost** [comment]
so with just crimson fluff, stomp the bean, athanasius, indri_lightfoot, pkmartini, podge and bozemanian devil in the skins and in the config newly created worlds work fine for me.

thought I narrowed the skins problem to just 3, looks like there could be more?

working config here  https://pastebin.com/V7Whp1th

**Comment by GenDeathrow** [comment]
I will look into fixing/catching the crash issue.  The custom skin resource loader was added in one of the last updates. Its still pretty new and no one really uses it. I figured I'd get a crash from it.  Also head drops prolly wont work since the gamertag is lost by changing the name and using custom skin loader.

**Comment by GenDeathrow** [comment]
Strange crash was apparently happening cause the size of the list of raiders was 0.  There always has to be at least one raider in a list. Had you disabled all raiders or just a single raider for this to happen? Either way I will make sure if the list is 0, I will have a default list.

**Comment by GenDeathrow** [comment]
Ok So I'm catching the error now. and will have a default skin in-case the raider skin list is empty.  

Also I found the issue causing the problem.  Line 75 on this [FILE](https://pastebin.com/Mq0juFNE) was missing a comma, so your raider file was failing to read. I may add an error notification(Or I'll just crash the game) in, but if you watch your console when you load minecraft it will say there was a json read error and gives you close the the line number.  I almost always use an online [JSON Validator](https://jsonlint.com/) to check my json configs. 

So technically a small parsing issue in your json helped me find another bug.

**Comment by ghost** [comment]
So something stupid as a missing comma?  lol  I do get some missing textures, like sides of heads not rendering. Thought it was optifine but happens when I remove optifine.  I use Mo Bends mod that I know causes things to not render on players like heads and parrots, even with its Player Render in the Config set to False, I'll do a bit of testing see if another mod is interferring

Thanks for all you have done

**Comment by GenDeathrow** [comment]
yeah, json exceptions don't jump out at ppl .
