### ISSUE TITLE
Raid difficulty issues

### ISSUE THREAD

**Issue by Yorkforce** [GenDeathrow/PlayerRaiders#2]
We set the I:"Raid Day Difficulty Progression"=100 but when logging in at day 40 it was already on Raid difficulty 5.

Also noticed if we ran the /time set day command it goes right back to day 0

**Comment by GenDeathrow** [comment]
Paste your config up here in pastebin. 

Also it goes off by world time so if the set command day turns it back to day 0 it doesnt deal with raiders that vanilla.

**Comment by GenDeathrow** [comment]
Use/ time add 24000.

**Comment by Yorkforce** [comment]
This is the config:
https://pastebin.com/fgBgMHQ4

Were basically an online always server so I wanted to slow down the raid progression alot, as its a new server not many players will join straight away which gives new players time to get onto the server without it starting on a very high raid difficulty.

I will keep the /time add command in mind, it wasn't actually a bad side effect resetting to day 0 due to the reasons above, we just noticed it when we performed the command.

**Comment by GenDeathrow** [comment]
Ok, I just tested it all and it seems to working as intended. Set it to 100 and it progressed on the server correctly. What type of server are you using? Sponge/Forge, OS, Java?

**Comment by GenDeathrow** [comment]
Wait.. I bet clients configs are still set to raid days 8, and the server doesn't sync its config to the clients. So it says that but its really not that. That.

**Comment by Yorkforce** [comment]
Aye SpongeForge Invasion modpack server, I guess if it's working ok on forge (hard for us to test due to network setup) then I wouldn't be overly surprised if it's a SpongeForge issue.

**Comment by GenDeathrow** [comment]
SpongForge has tons of issues, and I normally don't help with issues with that. 
But I think this is a server and client desync issues. Servers say one time clients think its another. << my idea.

Server actually sets the difficulty. but clients may not realize what the server is set to cause I don't sync it up. I didn't think about it. So if the client config file difficulty progression x days is set to 8 the client does the math wrong. 

So easiest way to check is if day is under 100 a majority of the mobs have 10 health and after day 100 they have 20+ health. Than its working just fine. The clients just have the wrong setting. I will make it sync up in a later update.. prolly next day or so.

**Comment by GenDeathrow** [comment]
OK the newest version came out. it will fix the issue with server and client thinking the day progression is different. But a new invasion update will be coming out soon. I rather you update to that. than update raiders.
