### ISSUE TITLE
[1.12] Unable to Tweak Raiders equipment

### ISSUE THREAD

**Issue by MasterEnderman** [GenDeathrow/PlayerRaiders#20]
Each time you modify the equipment files of the raiders, the files will be regenerated if you restart the game. that makes i currently impossible to tweak them.

Forge: 2739
Raiders: 3.0.6

**Comment by GenDeathrow** [comment]
.. crap I thought I had fixed this. I will look into it tomorrow. Thanks for bringing this up. Sorry for late response. I injured my back the other day, so couldn't sit at a computer.

**Comment by MasterEnderman** [comment]
no problem, take your time, but if you are at it, could you add a config for the shooting speed of the archers?

**Comment by GenDeathrow** [comment]
Ok I got it fixed and was able to add in your suggestion. That was a good suggestion by the way.. makes the archers class a bit more customize able. I also added in a max distance as well. update will be on its way as long as I dont run into any errors.

**Comment by GenDeathrow** [comment]
ok nvm.. I removed the range modifier it caused some issues with accuracy and would also cause issues with rangers having a hard time to lock onto a single target past its defaulted range.

**Comment by MasterEnderman** [comment]
Thank you for fixing it and adding that extra config option. keep up the good work. Cheers!
