### ISSUE TITLE
freeze upon loading raiders stuff in stage 5

### ISSUE THREAD

**Issue by TheNimbleNinja** [GenDeathrow/PlayerRaiders#22]
[Minecraft Ascention Alpha-7879.zip](https://github.com/GenDeathrow/PlayerRaiders/files/2292025/Minecraft.Ascention.Alpha-7879.zip)
i gave you an export of my mod pack as that is the only way i can give you information on this as it doesnt produce a crash

**Comment by GenDeathrow** [comment]
Did you get these resolved?
