### ISSUE TITLE
I get a ClassCastException on server connect

### ISSUE THREAD

**Issue by mczero80** [GenDeathrow/PlayerRaiders#23]
Hi, 
while the Raiders mod works most of the time, Minecraft often crashes when I try to connect to my private LAN server.

**Edit: I now get it every time.**

This is the crashlog, and it seems that Raiders mod is the cause. There are some other mods, but take a look into the crash report:

https://gist.github.com/GenDeathrow/9826fb3cb598672d9c5e8263531c16cf

**Comment by GenDeathrow** [comment]
ok it should be an easy fix. next time make sure to put the error/crash into pastbin.com or something of the like.

**Comment by mczero80** [comment]
Will do it! Thank you!
