### ISSUE TITLE
Raiders showing default skins when other skins are specified

### ISSUE THREAD

**Issue by darchitectlp** [GenDeathrow/PlayerRaiders#24]
Hey, so I have a bunch of new skins and names I added, but it looks like oftentimes the mod pulls textures to use out of the .jar instead of using my custom skins. And can you add an example to your wiki/mod curse page?

Edit: I just found this in your comments section "I'll get a tutorial eventually, but basically. Anything under 'assets/skins/filename.png' = 'raiders:skins/filename' Just make sure they are all lowercase, no spaces, no crazy special characters."

Is that right? Lowercase is required in the .png file name? Maybe that's what was messing the skins up...

**Comment by GenDeathrow** [comment]
Its best to keep everything lowercase, this is mainly because of an issue with windows and Linux, and Mac systems handle upper and lowercase filelocations all differently. So yest they all have to be lowercase ,including file names.

**Comment by darchitectlp** [comment]
Hey, so I tried lowercasing everything, and it didn't work. I've got Raiders still spawning with generic skins from the .jar. Strangely, they are picking up the outer skin layers from my custom skins... and the heads. 

[Edit] I just realized a lot of the skins in your jar don't have heads, which is why I guess my custom skins are visible for that body part.

**Comment by GenDeathrow** [comment]
can you imgur one of the skins your trying to replace with?

**Comment by darchitectlp** [comment]
https://imgur.com/a/UzamoQf

Here you can see his face and helmet, but then the default skin and default helmet over his.

**Comment by GenDeathrow** [comment]
oh.. your talking about my skin overlays.  if you dont want that, Than you can just turn it off in the confgs. under "settings.cfg > client > "Render Skin Overlays" = false" . 

Other than not its normal. It allows you to have randomly dressed mobs. Skin overlays are different from custom skinned mobs. if that makes sense. Think of it as random clothing is the basic concept.

Now if that doesn't work than there is a bug.

**Comment by darchitectlp** [comment]
Hahahaha! Too funny! I've spent awhile trying to fix this! Suggestion to make the config comment clearer in your file... Maybe something like "Randomly applies clothing overlays to Raiders." I thought that option was to turn off everything about all the skin options. Thanks!!!

**Comment by GenDeathrow** [comment]
It can be a little confusing sure, but I didn't say clothing cause there are other things other than clothing. There are some skins that add rotting zombie flesh. Which is why I call it an overlay. but I look at see if I can reword the comment above it.
