### ISSUE TITLE
Raiders health is the same regardless of class

### ISSUE THREAD

**Issue by Morozzs** [GenDeathrow/PlayerRaiders#27]
I have basic health for raiders in config set to 25. Normals raiders spawn with 25/25 health, but brutes, for example, have 25/56. For some reason they spawn with only half health. The others, forgot their class names, may have 25/12.

**Comment by GenDeathrow** [comment]
Thats a bug for sure.. looks like I still have some hard-coded stuff that messes with the custom health.  I try and get an update as soon as I can.
