### ISSUE TITLE
suggestion: it would be nice to be able to randomize the weight of the names on the skin list.

### ISSUE THREAD

**Issue by gravysamich** [GenDeathrow/PlayerRaiders#29]
as the title suggests, i am looking to randomize the weight each name gets. this would mean that sometimes 1 player is way more likely to show up but later may not show up for a long time. you could randomize these weights every few minecraft days.

**Comment by GenDeathrow** [comment]
I know this is an old post.. but finally getting some work done on the mod today. but This is already a thing. there is a weight on the raider_skins.json for this particular thing.
