### ISSUE TITLE
Multiple requests/quality of life improvements.

### ISSUE THREAD

**Issue by malwilson** [GenDeathrow/PlayerRaiders#3]
1: A discord server would be helpful

2: Config option to disable raiders from attacking passive mobs

3: More clear default config options 

    # Weight of Raiders spawning [range: 1 ~ 1000, default: 10]
    I:SpawnWeight=20

    # Changes dungeon spawner weight for raiders. Example is zombies are 200, where skeletons are 100. [range: 1 ~ 1000, default: 200]
    I:"Mob Spawner Weight"=20

these are pretty unclear as to actual usable statistics eg 1/100? 200%? as well as 

    # Meant for Twitch/Other sub whitelist. # One whitelist link per line. Example: http://whitelist.twitchapps.com/list.php?id=12345 [default: ] [default: ]
    S:WhiteLists <
     >

not too sure what that entails

4: Config option for chance of getting entire outfit or just parts of the outfit
for example
      "name": "Leather Armor Set",
      "head": "minecraft:leather_helmet",
      "body": "minecraft:leather_chestplate",
      "legs": "minecraft:leather_leggings",
      "feet": "minecraft:leather_boots",
      "head_nbt": {},
      "body_nbt": {},
      "legs_nbt": {},
      "feet_nbt": {},
      "always spawn full set": false,
     "chance of spawning with full set 25%"
      "weight": 25
    },

5:remove junk from offhand default config and add torch and shield
  "OffHand": [
    {
      "itemID": "minecraft:torch",
      "nbt": {},
      "weight": 10
    },
    {
      "itemID": "minecraft:shield",
      "nbt": {},
      "weight": 10
    }
  ],

6: re order the config based on importance

    I:"Raid Day Difficulty Progression"=5

is randomly in the middle of the file when it should be at the top seeing on how it is one of the most important settings their are a few more like this and its pretty anoying trying to find stuff
the entire ##########################################################################################################
# progessive difficulty
#--------------------------------------------------------------------------------------------------------#
# You can set what the raiders get on each Difficulty Increase
##########################################################################################################
should be at the top

7:general relook at the default settings they are pretty weird

8:spellchecking the config

sorry if this was a bit long or if it sounds really demanding, but i think if you had a look at some of these suggestions your mods usability would improve a ton.

**Comment by GenDeathrow** [comment]
1. https://invite.twitch.tv/AMpRToLaIEqxjYjialQtHA (I use curse/twitch)
2. reasonable option. atm i just have one for all entities. 
3. 
- The weight system is just like what normal vanilla weighting system. It really cant be any more clearer. "The chance that this spawn will be picked as compared to other spawn weights. Must be non-negative and at least 1." [sort of explination](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/modification-development/2341610-needing-a-detailed-explanation-of-mob-spawning)
- mob spawner same as above. They are compared to other spawning wegihts 
- if your a twitch streamer, and you have subs, there is a special url you can use to list all your subscribers. 
4. Those are for entire sets, but they get parts of those based on randomness. by x raid difficulty you will start to see them with that full set. 
5. Shields wont be junk for long as it will provide defense, but junk is there for a reason. (a modpack reason)
6. Re-Ordering is not an easy task, as the order is controlled by forge configuration files. normally based off of the alphabet. 
7. The default configs are set for a specific modpack (custom commissioned.). that's why I inform on the main page that this mod isn't pre-configured for normal play. 
8. I'm fully aware of the spellchecks, but when you change config file names than it will mess up others config files and create duplicates. Which I could catch, but I choose not too as most times it just messes up config files.

**Comment by malwilson** [comment]
im pretty iffy on curse as i remember when it was a virus site

also maybe add a setlevel difficulty command something like /raider setlevel -- 

and any idea how exactly i would lock "body" textures to a name it seems to be random -head
or even change textures around maybe pulling from a website or something

and do "friendly" raiders spawn in the same group as "hostile" raiders

again sorry if that sounds really demanding and thanks for the reply

**Comment by GenDeathrow** [comment]
Curse is very secure for the most part. And they scan most things. I have never known it to be a virus site. I have mainly used it for the last 2 years. Only time I heard anything was when someone got a single bad file on there in the last 2 years. 

you can set difficulty by just setting the day. 

raiders.cfg is what actually controls the skins. there are Defaults that always override. But for the most part raiders.cfg controls all the skins. I may add in some configs to turn off the defaults from overriding. 

I'm working on the friendly raiders spawning in non friendly raider groups. its been an issue. but haven't  had time to look into it yet.

and I don't mind the suggestion's as long, As ppl don't expect me to agree with every thing. I do have a specific idea for the direction of raiders. And I do appreciate some of the suggestions, that way some things can get explained better, or possible changed for the better.

**Comment by malwilson** [comment]
Im still not sure what 
    # Changes dungeon spawner weight for raiders. Example is zombies are 200, where skeletons are 100. [range: 1 ~ 1000, default: 200]
    I:"Mob Spawner Weight"=20
# Remove Vanilla Mob spawners from Dungeon Hooks [default: false]
    B:"Remove Vanilla Mob Spawner"=true
are i understand the weight system but im not sure what dungeon spawner weight is will it remove default spawners and replace them with raider spawners or something
and no idea what a Dungeon Hook is unless this is something for a modpack
with the 
    # Raiders will spawn reguardless of light levels. Basically Daytime Spawning. False sets it to Vanilla Spawning rules [default: true]
    B:"Spawn in Daylight"=false
not sure if its posible but a few spawning rules could be helpfull
while it would be interesting to have a hostile mob spawn durring the day i wouldent really like them spawning in my house constantly
so maybe a can spawn on "minecraft:grass,minecraft:sand" im pretty sure that would be the best option for mod compatibility with biomes o plenty and the like and avoiding the issue with glass roofs in your house or something

im also pretty sure that skins have no relation to the name of the player and adding a name to it just adds a head to the skin
and any idea if these raiders will spawn in biomes o plenty biomes
not sure why you would want but you should also have the ability to set the biomes they spawn in with a whitelist and blacklist of biome id's
possibly spawn weights by those biome id's
but again
not sure why you would want that just the option would be nice
and the command to change the level thing would be nice
as it seems to glitch out when you change the time on the server alot

they also always seem to drop random mob drops
even when i have them set to drop nothing
and it would be nice to have a option to set individual class base health
as im trying to get them all to have exactly 20 hp
and to get them to have the same walking speed a player has
as a single skeleton can kill 30 of these guys just walking backwards slowly
and you can just avoid them walking away
their also seems to not be a cap on the speed multiplyer
so eventually they would be moving so fast that the game would instantly crash trying to proccess their movement
and not sure if you could or if its out of the scope of the mod but disableing infighting would be pretty nice
so when a archer hits a friendly they all dont start killing eachother
i remember seeing a plugin that used to do that with the skeletons

i dont really think that twitch chat thing works propperly its really glitchy so im just going to use this

![2017-04-20_14 40 55](https://cloud.githubusercontent.com/assets/12958373/25257869/12d3b18c-25f0-11e7-9e14-09ad8044d01a.png)
