### ISSUE TITLE
Constantly receiving Raider death messages

### ISSUE THREAD

**Issue by happybandit360** [GenDeathrow/PlayerRaiders#30]
In the process of developing a modpack and I would like to use Raiders, but I am currently receiving CONSTANT death messages about the raiders who are dying from attacking vanilla mobs. I have tried turning off death messages (/gamerule showDeathMessages false) with no effect. Is there a way to prevent this from happening?

**Comment by GenDeathrow** [comment]
This is COFH not me. Check there config. you can turn it off
