### ISSUE TITLE
Don't attack creepers option // mob attack blacklist

### ISSUE THREAD

**Issue by jemsztm** [GenDeathrow/PlayerRaiders#31]
Could you make a blacklist option for mobs to make them not attack them causing unnessessary destruction in random locations. People might not want to see the landscape of bombarded Berlin in WW2 around them

**Comment by GenDeathrow** [comment]
yeah that actually may not be a bad idea. The original idea was developed for a wasteland modpack. So destruction fit it. May be a while for an update but I will look into it.
