### ISSUE TITLE
Game Crashed: Initializing game

### ISSUE THREAD

**Issue by DatrixTHLK** [GenDeathrow/PlayerRaiders#34]
Hi GenDeathrow, 

Minecraft 1.12.2
Forge 14.23.5.2838
Raiders 3.0.9
I keep getting this crash when trying to start the game.
Crash Report: https://paste.dimdev.org/coreqokidi.mccrash

**Comment by GenDeathrow** [comment]
~~Is this happening with a new world or old world?~~

Nvm you said its when starting game...

**Comment by GenDeathrow** [comment]
Its saying the entity is registered twice. But thats not happening in my code.. I dont think this would happen.. but is there only one raiders mod in the mod folder?

**Comment by GenDeathrow** [comment]
Is there another mod that is adding a raider entity?

**Comment by DatrixTHLK** [comment]
Oh...yes it was registered twice. I'm unaware of another mod that would do this type of thing. I have a hunch though that it is within an RPG mod or Adventure mod I downloaded besides your own. There was only one raiders mod in the mod folder at the time. I didn't see any other mods that had the word raiders in them. 

**Update:** Found the mod in question. It was called the Prince of Persia mod.

**Comment by DatrixTHLK** [comment]
Found the mod in question. It was called the Prince of Persia mod.

**Comment by GenDeathrow** [comment]
Ok his code was not on github, but was able to decompile the mod. Looks like he has same class name as me and also named it a raider. I had thought a certain naming I used during registration prevented this.. it apparently doesn't. This mod was made with MCreator. So I would't expect it to get changed on their side.  And I cant really fix mine either as the countless number of modpacks that have already included my mod could cause old worlds to crash. But in the future I know now I need to add to the secondary naming.

**Comment by DatrixTHLK** [comment]
Thanks for the response! I appreciate it.
