### ISSUE TITLE
Raider setting block on fire fails with exception -generates massive log file

### ISSUE THREAD

**Issue by SteelGiant87** [GenDeathrow/PlayerRaiders#4]
I have been running an invasion 1.0.5 server for 3 hours with two players and found that the folder had grown to 8GB in that time. It turns out that all the increase in size was down to one 8GB log file filled with:

[11:50:35] [Server thread/DEBUG] [playerraiders/]: Raider couldn't set block on fire...java.lang.NullPointerException

Analysing the first million lines of the log file:

PS C:\Games\Minecraft\Invasion\Backups\Invasion 1.0.5 Server\logs> (Get-Content .\fml-server-latest.log -Head 1000000 | select-string -pattern "Raider could").length
988668

so 98.8% of the first million lines is that exception.

Server is running on Windows 10 with java 1.8.0_121

Server is being launched with:

java -Xmx5G -Xms1G -jar forge-1.10.2-12.18.3.2254-universal.jar nogui

I haven't seen any raiders setting things on fire that I can be certain of. There have been a few trees nearby that have been set on fire, but we didn't see how or why. We are up to about day 10. Only noticeable issues were occasional stuttering (with no discernible cause), but only a few times over the 3 hours. These could quite easily have been due writing many GB of logs suddenly, but I don't know if the times match up.

**Comment by GenDeathrow** [comment]
Already known.. putting a fix out today. Thanks for reporting.

**Comment by frenchiveruti** [comment]
Hey, is this fixed already? Just want to know the commit that's associated with this issue, thanks.
Also, is there a way to heal Friendly Raiders? Or just be sad when they get killed.

**Comment by GenDeathrow** [comment]
Yes its fixed in the newest versions..

**Comment by GenDeathrow** [comment]
just be sad when they die, I wanted to make them follow you and be your friends. but when I set everything up I failed at making it easy to convert the code over.

**Comment by GenDeathrow** [comment]
Actually I will leave this open for a while.

**Comment by GenDeathrow** [comment]
Is fixed in latest version of the in vision mod pack v1.0.6

**Comment by frenchiveruti** [comment]
Ok, great! Let's say it's closed when .0.6 it's released :smile:
