### ISSUE TITLE
Setting raider level not having any effect

### ISSUE THREAD

**Issue by macman73** [GenDeathrow/PlayerRaiders#6]
I run a public Invasion server over at invasion.chilliserver.com and as I am sure you know the Players raiders mod is in that pack.
Version: PlayerRaiders-1.10.2-1.3.16.jar
Forge: forge-1.10.2-12.18.3.2281-universal.jar
Sponge: spongeforge-1.10.2-2281-5.2.0-BETA-2328.jar
As new players arrive on the server its very useful to be able to turn the difficulty level of raiders down to give them a chance.
So I run /pr setlevel 0 or /pr setlevel 1
This seems to lower thier health but for some reason they have a lot of speed and hit like steam trains.
Here is my config https://pastebin.com/q2jKS1th

Also is it usual that if I do /time set day it resets the day count to zero

I assuming the raider settings get written to some file somewhere can you tell me where this happens so I can maybe do some manual edit, obviously I will create backups etc.

Thanks for reading

**Comment by GenDeathrow** [comment]
Raider difficulty is set by what day it is. Raider set level only does the math for you and sets the day. Speed and hit dmg don't really change on what difficukty.. The speed is random. But as the difficulty goes up raiders have a higher change to gain more speed.  Difficulty changes how often you see special raider classes, armor/weapon, health, some raiders get a bonus speed buff. So it's techinically working as intended.
