### ISSUE TITLE
Crash[Ticking Player] Drink milk while Serum-B active

### ISSUE THREAD

**Issue by AileRozy** [GenDeathrow/PlayerRaiders#8]
[crash-2017-12-26_16.21.48-server.txt](https://github.com/GenDeathrow/PlayerRaiders/files/1586958/crash-2017-12-26_16.21.48-server.txt)
Drink milk while Serum-B active crash the server side.
tested in solo with creative and survival, same result.
the potion effect still there while load the world after crash.

**Comment by GenDeathrow** [comment]
Hum I will check into that.  make sure to add in your versions also, but the minecraft and raiders versions. I can see its 1.10, but its good to have all that information.

**Comment by GenDeathrow** [comment]
Ok I realize this has been a bug for a while.. but I finally got time to look at it.. and figured the issue out. So hopefully I will get an update to fix this issue next couple days.

**Comment by GenDeathrow** [comment]
This was fixed.
