### ISSUE TITLE
[Bugs] Dupe bugs. 

### ISSUE THREAD

**Issue by Akitori** [GenDeathrow/PlayerRaiders#9]
3.0.0 raiders, for 1.12.2

bug in action:

https://youtu.be/gufRCxpf1mU

**Comment by GenDeathrow** [comment]
Lol nice video. Yeah that's a pretty bad bug, but that's why I have it under beta. Bugs will happen. But glad you noticed this so quick. As far as the chest stealing AI, something may have broken between ports, So I will also take a look at that. But perfect way to show bugs. 2 thumbs up.

**Comment by GenDeathrow** [comment]
should be fixed in 3.0.1
